# Generated by Django 5.1.2 on 2024-12-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandicraftProduct',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.products')),
            ],
            bases=('app.products',),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
