# Generated by Django 5.1.2 on 2024-12-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_handicraftproduct_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialCoffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
