# Generated by Django 5.1.2 on 2024-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_handicraftproduct_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.DeleteModel(
            name='HandicraftProduct',
        ),
    ]
