# Generated by Django 5.1.2 on 2024-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_specialhandicraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='landingBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
